name: "CustomCheck"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run Checks"
    strategy:
      fail-fast: false
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: "1.21.x"
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        install-go: false
        cache-key: "1.21.x"
