name: Build+Test Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get CMake
      uses: symbitic/install-cmake@master

    - name: Cache OpenCV
      uses: UrielCh/opencv-cache-action@V1
      with:
        branch: 4.x
        BUILD_LIST: core,imgproc,imgcodecs,videoio,highgui,video,calib3d,features2d,objdetect,dnn,ml,photo,gapi,python3
        NO_CONTRIB: ''
      
    - name: Build project with make
      run: make build

    - name: Run tests
      run: go test -v
